version: '3'
services:
    maildev:
        image: maildev/maildev
        ports:
          - 1025:25
    server:
        build: .
        ports:
          - 3002:3000 # ordinateur:conteneur docker, port conteneur docker == port dans fichier index
        command: npm run dev
        volumes: #chemin
          - ./src/:/app/src/
        depends_on:
          db:
            condition: service_healthy
    db:
      #container_name: toto
      image: mysql
      cap_add:
        - SYS_NICE
      command: mysqld --default-authentication-plugin=mysql_native_password
      # restart: always
      environment:
        MYSQL_DATABASE: 'chickpeas_db'
        MYSQL_ROOT_PASSWORD: 'Wild2022!'
      ports:
        - 3306:3306
      #expose: #Pas utile pour nous actuellement
      #- '3306'
      volumes: #anonyme (sans :) // #nommé => delegue a docker pour pouvoir retrouver les données après
        - /var/lib/mysql
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
