version: '3'
services:
    maildev:
        image: maildev/maildev
        ports:
          - 1025:80
    server:
        build: .
        ports:
          - 3002:3000 # ordinateur:conteneur docker, port conteneur docker == port dans fichier index
        command: npm run dev
        env_file: 
          - .env
        volumes: #chemin
          - ./src/:/app/src/
        depends_on:
          db:
            condition: service_healthy
    db:
        #container_name: toto
        image: mysql
        cap_add:
          - SYS_NICE
        command: mysqld --default-authentication-plugin=mysql_native_password
        # restart: always
        env_file: 
          - .env
        ports:
          - 3307:3306
        #expose: #Pas utile pour nous actuellement
        #- '3306'
        volumes: #anonyme (sans :) // #nommé => delegue a docker pour pouvoir retrouver les données après
          - /var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
